[package]
name = "usftp"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "3.0.14"
remotefs = "^0.2.0"
remotefs-ssh = "^0.1.0"
thiserror = "1.0.30"
log = "0.4"
env_logger = "0.9.0"